/**
 * Automations: every scheduled job this machine knows about, read-only.
 * Sources: ~/.claude/tasks, the user crontab, ~/Library/LaunchAgents, and the
 * artifacts this app generated (which are labeled generated-not-installed
 * until they show up in a real scheduler).
 */

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { WORKFORCE_HOME } from "./config";

export interface AutomationRow {
  name: string;
  source: "claude" | "crontab" | "launchd" | "workforce";
  cadence: string;
  detail: string;
  updatedAt: number;
  status: "installed" | "generated" | "unknown";
}

function claudeTasks(): AutomationRow[] {
  const dir = path.join(process.env.CLAUDE_CONFIG_DIR ?? path.join(os.homedir(), ".claude"), "tasks");
  if (!existsSync(dir)) return [];
  const rows: AutomationRow[] = [];
  for (const name of readdirSync(dir).slice(0, 40)) {
    if (name.startsWith(".")) continue;
    const abs = path.join(dir, name);
    try {
      const st = statSync(abs);
      rows.push({
        name: name.replace(/\.(json|md)$/i, ""),
        source: "claude",
        cadence: "—",
        detail: `~/.claude/tasks/${name}`,
        updatedAt: st.mtimeMs,
        status: "installed",
      });
    } catch {
      /* skip unreadable */
    }
  }
  return rows;
}

function crontabRows(): AutomationRow[] {
  try {
    const out = execFileSync("crontab", ["-l"], { encoding: "utf8", timeout: 4000, stdio: ["ignore", "pipe", "ignore"] });
    return out
      .split("\n")
      .filter((l) => l.trim() && !l.trim().startsWith("#"))
      .slice(0, 30)
      .map((line) => {
        const m = /^(\S+\s+\S+\s+\S+\s+\S+\s+\S+)\s+(.*)$/.exec(line.trim());
        return {
          name: m ? m[2].slice(0, 60) : line.slice(0, 60),
          source: "crontab" as const,
          cadence: m ? m[1] : "?",
          detail: line.trim().slice(0, 160),
          updatedAt: 0,
          status: "installed" as const,
        };
      });
  } catch {
    return [];
  }
}

function launchdRows(): AutomationRow[] {
  if (process.platform !== "darwin") return [];
  const dir = path.join(os.homedir(), "Library", "LaunchAgents");
  if (!existsSync(dir)) return [];
  const rows: AutomationRow[] = [];
  for (const name of readdirSync(dir)) {
    if (!name.endsWith(".plist")) continue;
    const abs = path.join(dir, name);
    try {
      const st = statSync(abs);
      const text = readFileSync(abs, "utf8");
      const hour = /<key>Hour<\/key>\s*<integer>(\d+)<\/integer>/.exec(text)?.[1];
      const minute = /<key>Minute<\/key>\s*<integer>(\d+)<\/integer>/.exec(text)?.[1];
      rows.push({
        name: name.replace(/\.plist$/, ""),
        source: "launchd",
        cadence: hour !== undefined ? `daily ${hour.padStart(2, "0")}:${(minute ?? "0").padStart(2, "0")}` : "see plist",
        detail: abs,
        updatedAt: st.mtimeMs,
        status: "installed",
      });
    } catch {
      /* skip */
    }
  }
  return rows;
}

function workforceRows(installedNames: Set<string>): AutomationRow[] {
  const dir = path.join(WORKFORCE_HOME, "automations");
  if (!existsSync(dir)) return [];
  const rows: AutomationRow[] = [];
  for (const name of readdirSync(dir)) {
    if (!/\.(plist|crontab)$/.test(name)) continue;
    const abs = path.join(dir, name);
    try {
      const st = statSync(abs);
      const bare = name.replace(/\.(plist|crontab)$/, "");
      rows.push({
        name: bare,
        source: "workforce",
        cadence: "daily 07:00",
        detail: abs,
        updatedAt: st.mtimeMs,
        // Honest state: generated by this app ≠ running. It counts as installed
        // only when the same job name shows up in a real scheduler.
        status: installedNames.has(bare) ? "installed" : "generated",
      });
    } catch {
      /* skip */
    }
  }
  return rows;
}

export function listAutomations(): AutomationRow[] {
  const launchd = launchdRows();
  const cron = crontabRows();
  const installedNames = new Set([...launchd.map((r) => r.name), ...cron.map((r) => r.name)]);
  // A generated crontab line is "installed" when the live crontab mentions the dream endpoint.
  if (cron.some((r) => r.detail.includes("/api/dream"))) installedNames.add("dream");
  return [...claudeTasks(), ...launchd, ...cron, ...workforceRows(installedNames)].sort(
    (a, b) => b.updatedAt - a.updatedAt,
  );
}
