/**
 * 1Password as the secure secrets runtime — via the `op` CLI when present.
 *
 * What this module does:
 *   - detects the CLI and whether it is signed in (`op whoami`)
 *   - stores providerId → op://vault/item/field mappings (the mapping file
 *     holds references only, never secret values)
 *   - resolves references at call time with `op read` (cached briefly)
 *   - generates a .env template of op:// references for `op run`
 *   - scans text for leaked-looking secrets before anything is written out
 *
 * When the CLI is absent everything degrades to an honest setup-needed state;
 * the local credentials file remains the fallback store.
 */

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { WORKFORCE_HOME, which } from "./config";
import { PROVIDERS, PROVIDER_BY_ID } from "./credentials";

export const DEFAULT_VAULT = "BaselineOS";
const MAPPING_PATH = path.join(WORKFORCE_HOME, "onepassword.json");

// ── CLI detection ───────────────────────────────────────────────────────────

export interface OpStatus {
  installed: boolean;
  bin: string | null;
  signedIn: boolean;
  account: string | null;
  detail: string;
}

export function opStatus(): OpStatus {
  const bin = which("op");
  if (!bin) {
    return {
      installed: false,
      bin: null,
      signedIn: false,
      account: null,
      detail: "`op` (1Password CLI) was not found on this machine",
    };
  }
  try {
    const out = execFileSync(bin, ["whoami"], { encoding: "utf8", timeout: 5000, stdio: ["ignore", "pipe", "pipe"] });
    const account = /email:\s*(\S+)/i.exec(out)?.[1] ?? out.trim().split("\n")[0] ?? null;
    return { installed: true, bin, signedIn: true, account, detail: `signed in${account ? ` as ${account}` : ""}` };
  } catch {
    return { installed: true, bin, signedIn: false, account: null, detail: "installed but not signed in — run: op signin" };
  }
}

// ── op:// references ────────────────────────────────────────────────────────

const OP_REF = /^op:\/\/([^/]+)\/([^/]+)\/(.+)$/;

export function parseOpReference(ref: string): { vault: string; item: string; field: string } | null {
  const m = OP_REF.exec(ref.trim());
  return m ? { vault: m[1], item: m[2], field: m[3] } : null;
}

export function buildOpReference(item: string, field = "credential", vault = DEFAULT_VAULT): string {
  return `op://${vault}/${item}/${field}`;
}

/** Resolve one reference. Short cache so a page render doesn't shell out per widget. */
const opCache = new Map<string, { at: number; value: string | null }>();
const OP_CACHE_TTL = 30_000;

export function opRead(ref: string): string | null {
  if (!parseOpReference(ref)) return null;
  const cached = opCache.get(ref);
  if (cached && Date.now() - cached.at < OP_CACHE_TTL) return cached.value;
  const bin = which("op");
  let value: string | null = null;
  if (bin) {
    try {
      value = execFileSync(bin, ["read", ref], { encoding: "utf8", timeout: 8000, stdio: ["ignore", "pipe", "pipe"] }).trim() || null;
    } catch {
      value = null;
    }
  }
  opCache.set(ref, { at: Date.now(), value });
  return value;
}

/** Validate without exposing: does the reference parse, and does it resolve right now? */
export function validateReference(ref: string): { parses: boolean; resolves: boolean } {
  const parses = Boolean(parseOpReference(ref));
  return { parses, resolves: parses ? Boolean(opRead(ref)) : false };
}

// ── provider → reference mappings ───────────────────────────────────────────

export function readOpMappings(): Record<string, string> {
  try {
    if (!existsSync(MAPPING_PATH)) return {};
    return JSON.parse(readFileSync(MAPPING_PATH, "utf8")) as Record<string, string>;
  } catch {
    return {};
  }
}

export function setOpMapping(providerId: string, ref: string | null): void {
  if (!PROVIDER_BY_ID[providerId]) throw new Error(`unknown provider: ${providerId}`);
  if (ref && !parseOpReference(ref)) throw new Error("reference must look like op://vault/item/field");
  const mappings = readOpMappings();
  if (ref) mappings[providerId] = ref;
  else delete mappings[providerId];
  mkdirSync(WORKFORCE_HOME, { recursive: true });
  const tmp = `${MAPPING_PATH}.tmp`;
  writeFileSync(tmp, JSON.stringify(mappings, null, 2), { mode: 0o600 });
  renameSync(tmp, MAPPING_PATH);
  opCache.clear();
}

// ── .env template for `op run` ──────────────────────────────────────────────

/**
 * A template of references (no secrets) usable as
 *   op run --env-file=.env.op.template -- <command>
 */
export function generateEnvTemplate(): string {
  const mappings = readOpMappings();
  const lines: string[] = [
    "# Generated by Baseline AI Workforce — references only, safe to commit.",
    `# Usage: op run --env-file=.env.op.template -- <command>`,
    "",
  ];
  for (const p of PROVIDERS) {
    const ref = mappings[p.id];
    if (!ref || !p.envKeys.length) continue;
    lines.push(`${p.envKeys[0]}=${ref}`);
  }
  return `${lines.join("\n")}\n`;
}

// ── leak scanning ───────────────────────────────────────────────────────────

/** Patterns that look like real secrets — used to check text before it is written anywhere shareable. */
export const LEAK_PATTERNS: { name: string; re: RegExp }[] = [
  { name: "OpenAI-style key", re: /sk-[A-Za-z0-9_-]{20,}/ },
  { name: "Anthropic key", re: /sk-ant-[A-Za-z0-9_-]{20,}/ },
  { name: "OpenRouter key", re: /sk-or-v\d-[A-Za-z0-9-]{20,}/ },
  { name: "GitHub token", re: /gh[pousr]_[A-Za-z0-9]{30,}/ },
  { name: "Slack token", re: /xox[baprs]-[A-Za-z0-9-]{10,}/ },
  { name: "AWS access key id", re: /\bAKIA[0-9A-Z]{16}\b/ },
  { name: "Google API key", re: /\bAIza[0-9A-Za-z_-]{30,}\b/ },
  { name: "Private key block", re: /-----BEGIN [A-Z ]*PRIVATE KEY-----/ },
  { name: "Generic assigned secret", re: /(?:api[_-]?key|secret|token|password)\s*[:=]\s*["']?[A-Za-z0-9_\-/+]{24,}/i },
];

export interface LeakHit {
  pattern: string;
  /** Line number (1-based) and a redacted excerpt — never the matched secret itself. */
  line: number;
  excerpt: string;
}

export function scanTextForLeaks(text: string): LeakHit[] {
  const hits: LeakHit[] = [];
  const lines = text.split("\n");
  lines.forEach((line, i) => {
    for (const { name, re } of LEAK_PATTERNS) {
      const m = re.exec(line);
      if (!m) continue;
      const redacted = line.replace(m[0], `${m[0].slice(0, 4)}…[redacted]`);
      hits.push({ pattern: name, line: i + 1, excerpt: redacted.trim().slice(0, 120) });
    }
  });
  return hits;
}

export const OP_MAPPING_PATH = MAPPING_PATH;
